apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
type: Opaque
data:
  access-key: bWluaW9hZG1pbg==  # base64 encoded 'minioadmin'
  secret-key: bWluaW9hZG1pbg==  # base64 encoded 'minioadmin' 